### ISSUE TITLE
Does it work with multiple instances? 

### ISSUE THREAD

**Issue by pawansingh00** [RocketChat/meteor-streamer#34] opened 2018-09-24 07:35 UTC
Earlier I was using `arunoda:cluster` which has an `sync` method that I was using for `arunoda:streams`.

`  const streamer = new Meteor.Streamer('chat');
   Meteor.Cluster.sync(streamer);
`

Now that I switched to `rocketchat:streamer` How will I sync these?

**Comment by maxnowack** [comment] 2018-09-24 07:41
duplicate of #8, #26 and #33

**Closed** 2022-12-30 20:23 UTC
